export const userActionType  = {
    "GET_ALL_USER_LIST" : "GET_ALL_USER_LIST",
    "GET_ALL_USER_LIST_SUCCESSED" : "GET_ALL_USER_LIST_SUCCESSED",
    "GET_ALL_USER_LIST_FAILED" : "GET_ALL_USER_LIST_FAILED",
    "DISPLAY_USER_DETAIL" : "DISPLAY_USER_DETAIL",
    'CREATE_NEW_USER' : "CREATE_NEW_USER",
    'CREATE_NEW_USER_SUCCEDED' : "CREATE_NEW_USER_SUCCEDED",
    'CREATE_NEW_USER_FAILED' : "CREATE_NEW_USER_FAILED",
    "UPDATE_EXISTING_USER" : "UPDATE_EXISTING_USER",
    "UPDATE_EXISTING_USER_SUCCEDED" : "UPDATE_EXISTING_USER",
    "UPDATE_EXISTING_USER_FAILED" : "UPDATE_EXISTING_USER_FAILED",
    'DELETE_EXISTING_USER' : "DELETE_EXISTING_USER",
    'DELETE_EXISTING_USER_SUCCEDED' : "DELETE_EXISTING_USER_SUCCEDED",
    'DELETE_EXISTING_USER_FAILED' : "DELETE_EXISTING_USER_FAILED",
    
}